### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by CollinSchneider** [CollinSchneider/WhosGotNext#1]
Keep getting an application error and can't pin it. Not sure if I'm missing a step, but I don't think it's liking my start point in my package.json....

2016-02-16T15:06:51.358198+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-02-16T15:06:51.358197+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:236
2016-02-16T15:06:51.358199+00:00 app[web.1]:                                       ^
2016-02-16T15:06:51.358206+00:00 app[web.1]:     at Object.exports._errnoException (util.js:856:11)
2016-02-16T15:06:51.358205+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2016-02-16T15:06:51.358207+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:879:20)
2016-02-16T15:06:51.358208+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete](net.js:1053:14)
2016-02-16T15:06:51.334785+00:00 app[web.1]: listening on port  8080
2016-02-16T15:06:51.409298+00:00 app[web.1]: npm ERR! whos_got_next@1.0.0 start: `node app.js`
2016-02-16T15:06:51.409798+00:00 app[web.1]: npm ERR! Failed at the whos_got_next@1.0.0 start script 'node app.js'.
2016-02-16T15:06:51.410627+00:00 app[web.1]: npm ERR!     node app.js
2016-02-16T15:06:51.403804+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-02-16T15:06:51.408861+00:00 app[web.1]: npm ERR! npm  v3.6.0
2016-02-16T15:06:51.409118+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-02-16T15:06:51.409448+00:00 app[web.1]: npm ERR! Exit status 1
2016-02-16T15:06:51.421290+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-02-16T15:06:51.375320+00:00 app[web.1]: 
2016-02-16T15:06:51.403375+00:00 app[web.1]: npm ERR! Linux 3.13.0-71-generic
2016-02-16T15:06:51.410155+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the whos_got_next package,
2016-02-16T15:06:51.411271+00:00 app[web.1]: npm ERR!     npm owner ls whos_got_next

**Comment by rapala61** [comment]
do you have MONGOLabs addon installed in your app? https://devcenter.heroku.com/articles/mongolab#adding-mongolab-as-a-heroku-add-on

**Comment by CollinSchneider** [comment]
I have it installed now, however I'm still getting some errors I can't figure out

**Comment by rapala61** [comment]
Let's meet outside

**Comment by rapala61** [comment]
in person
